# Pre-commit hooks for Audibook Studio
# Ensures code quality across JavaScript/TypeScript and Python

repos:
  # General hooks for all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # JavaScript/TypeScript formatting and linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|html|md|yaml|yml)$
        exclude: |
          (?x)^(
            .*\.min\.(js|css)$|
            node_modules/|
            dist/|
            coverage/|
            \.next/|
            \.nx/|
            apps/python-worker/
          )

  # ESLint for JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: |
          (?x)^(
            node_modules/|
            dist/|
            coverage/|
            \.next/|
            \.nx/|
            apps/python-worker/
          )
        args: ['--fix']
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'
          - 'eslint@^8.56.0'

  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^apps/python-worker/.*\.py$
        language_version: python3.11

  # Python import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^apps/python-worker/.*\.py$
        args: ['--profile', 'black']

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^apps/python-worker/.*\.py$
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^apps/python-worker/.*\.py$
        exclude: ^apps/python-worker/tests/
        additional_dependencies:
          - types-redis
          - types-psycopg2
        args: ['--ignore-missing-imports']

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$

  # Commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [optional-scope]

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'
