services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/audibook
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - NODE_ENV=development
      - LOG_LEVEL=debug  # For basic logging
    depends_on:
      - db
      - redis
      - nats

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audibook
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"  # NATS client port
      - "8222:8222"  # NATS monitoring port
    volumes:
      - nats_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: test-access-key
      MINIO_ROOT_PASSWORD: test-secret-key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  python-worker:
    build:
      context: .
      dockerfile: apps/python-worker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/audibook
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - PHONIKUD_MODEL_PATH=/app/models/phonikud-1.0.onnx
      - LOG_LEVEL=info
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - SERVICE_NAME=python-worker
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
      - nats
      - loki
    volumes:
      - ./apps/python-worker:/app:cached
    restart: unless-stopped
    
volumes:
  postgres_data:
  minio_data:
  nats_data: